org: tenantutec123
service: api-comentario

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  environment:
    BUCKET_NAME: ${self:service}-${sls:stage}-ingesta-bucket

functions:
  guardarEnBucket:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario/guardar
          method: post
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: 
          - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"

resources:
  Resources:
    S3BucketIngesta:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - "*"
              MaxAge: 3000

  Outputs:
    BucketName:
      Value: !Ref S3BucketIngesta
      Export:
        Name: ${self:service}-${sls:stage}-bucket-name
